program: run_train_model.py
method: grid
metric:
  name: "Test/CF-total"
  goal: minimize
name: "law-sim"                # This is the name of the sweep
project: "NeurIPS24-CVAE"  # This is the project the sweep should be placed under
entity: ""

parameters:
  run:
    values: [1,2,3,4,5]
  use_label:
    values: [True]
  dataset:
    values: ["law"]
  a_y:
    values: [1]
  a_r:
    values: [1]
  a_d:
    values: [1]
  a_f:
    values: [0]
  u_kl:
    values: [1]
  u_dim:
    values: [3]
  n_epochs:
    values: [2000]
  lr:
    values: [0.001]
  model:
    values: ["cvae"]
  normalize:
    values: [True]
  global_path:
    values: ["saved/final"]
  dataset_root:
    values: ['../VAE/saved/final']
command:
  - ${interpreter}
  - ${program}
  - ${args_no_boolean_flags}
  - "--sweep"

